#!/bin/bash
       if ! grep  --only-matching hair <<< $I &> /dev/null; then
           echo "You have found a lock of the **hair** of a god!"
           echo "Add it to your inventory."
       else 
           echo "This treasure has already been taken."
       fi
