#!/bin/bash
             if ! grep  --only-matching platinum <<< $I &> /dev/null; then
                 echo "You have found a sack full of *platinum* coins!"
                 echo "Add it to your inventory." 
             else
                 echo "This treasure has already been taken."
             fi
