#!/bin/bash
            if ! grep  --only-matching emerald <<< $I &> /dev/null; then
                echo "You have found an *emerald*!"
                echo "Add it to your inventory."
            else
                echo "This treasure has already been taken."
            fi
